version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-iceberg-catalog
    environment:
      POSTGRES_USER: pg_user
      POSTGRES_PASSWORD: xxxxx
      POSTGRES_DB: iceberg-metastore-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
